components:
  schemas:
    "": {}
  securitySchemes:
    AuthorizationHeader:
      description: Input your token
      scheme: bearer
      type: http
info:
  contact:
    email: abce@email.com
    name: Parvez
  description: API usually works as expected. But sometimes its not true.
  license:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: http://someurl.oxox
  title: Backend API
  version: 1.0.0
openapi: 3.0.0
paths:
  /restaurants:
    get:
      description: ' Returns a list of restaurants based on filter request'
      parameters:
      - description: count of restaurants
        in: query
        name: count
        schema:
          description: count of restaurants
          format: int64
          type: integer
      - description: offset limit count
        example: "100"
        in: query
        name: offset
        schema:
          description: offset limit count
          format: int64
          type: integer
      - description: extra field
        in: query
        name: extra.field
        schema:
          description: extra field
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/'
          description: ""
      summary: Get restaurants list
security:
- AuthorizationHeader:
  - read
  - write
servers:
- description: ' Server-1'
  url: http://www.fake.com
- description: ' Server-2'
  url: http://www.fake2.com
